In [1]:
# 0.1 Cronología:

# 1. Se estudia a nivel estadístico las características de las variables originales,
#    Assurance y Matching. Se llega a la conlusión que Assurance al explicar directamente
#    a Matching, que es prescindible para evitar redundancias.

# 2. A nivel econométrico se pone a prueba el modelo original, lo cual dará indirectamente
#    luz verde a la inclusión de Matching, ya que las variables en su conjunto son significativas.

# 3. Finalmente para certificar si Matching es necesario y relevante en el modelo, se va a
#    comparar los rendimientos de algoritmos kNN y de árboles de decisión.
#    Esto servirá como confirmación final de qué modelo es el idóneo para predecir las contrataciones
#    en función del perfil ofertado.

# ATENCIÓN: en este caso se va a utilizar el fichero 6 que SÍ incluye la columna Matching, por
#           lo que se va a poner a prueba el modelo mejorado.

In [2]:
# 1. Importamos todas las librerías que creemos útiles

import io # Provee diferentes tipos de E/S: texto E/S, binario E/S e E/S.

import os # Leer o escribir un archivo.

import math # Proporciona acceso a las funciones matemáticas definidas en C.

import csv # Para cargar y manejar CSV.

import xlrd # Funcionalidades de excel en Python (1/2).

import xlwt # Funcionalidades de excel en Python (2/2).

import sklearn # Funcionalidades de Machine Learning.

import numpy as np # Manejo de datos extremadamente rápido cálculo numérico.

import scipy as sp # Módulos para optimización, álgebra lineal, etc.

import pandas as pd # Módulos de gestión de ficheros y dataframes.

import matplotlib.pyplot as plt # Generación de gráficos.

import statsmodels.api as sm # Módulo estadístico.

import random # Para fijar resultados.

In [3]:
# 2. Cargamos y leemos el fichero6.

fichero6 = pd.read_csv(r'C:\Users\jlc15\Desktop\MECOFIN\2º Cuatrimestre\TFM\Y - Ficheros Python\fichero6.csv')

fichero6

Gender  Education  Work Exp  Programming Exp  Matching  Status
0         0          1         0                0         0       0
1         1          1         0                1         1       1
2         1          1         1                0         1       1
3         1          1         0                0         0       0
4         1          0         1                0         0       1
..      ...        ...       ...              ...       ...     ...
824       1          1         0                0         1       1
825       1          1         1                0         1       1
826       1          1         0                1         0       0
827       1          1         0                0         1       1
828       1          1         1                0         1       1

[829 rows x 6 columns]

In [4]:
# 3. Algoritmos de clasificación con kNN:

from sklearn.model_selection import train_test_split

from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import accuracy_score

from sklearn.metrics import confusion_matrix

In [30]:
# 3.1.1 Intento 1: kNN predeterminado con la distancia de Euclídea.

# La distancia euclidiana es una métrica de distancia que se utiliza para datos continuos.

x = fichero6.iloc[:, :-1] # Seleccionamos todas las columnas excepto la última

y = fichero6.iloc[:, -1] # Elegimos sólo la última columna

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25)

knn = KNeighborsClassifier(n_neighbors=300) # Ajustamos el parámetro 'k'.

knn.fit(x_train, y_train)

y_pred = knn.predict(x_test)

accuracy = accuracy_score(y_test, y_pred)

print(f'Precisión: {accuracy}')

Precisión: 0.7932692307692307


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [31]:
# 3.1.2 Intento 1: matriz de confusión.

x = fichero6.iloc[:, :6]

y = fichero6['Status']

# Escogemos k=8 porque es el óptimo.

knn = KNeighborsClassifier(n_neighbors=8)

knn.fit(x, y)

y_pred = knn.predict(x)

confm = confusion_matrix(y, y_pred)

print(confm)

[[259   0]
 [  0 570]]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [7]:
# 3.1.3 Intento 1: resultados del kNN según parámetro 'k'.

# Intento 1: k = 2 --> 89.90%.

# Intento 2: k = 4 --> 90.86%.

# Intento 3: k = 6 --> 94.71%. Máximo.

# Intento 4: k = 8 --> 94.71%. Óptimo.

# Intento 5: k = 10 --> 93.75%.

# Intento 6: k = 20 --> 93.75%.

# Intento 7: k = 40 --> 92.30%.

# Intento 8: k = 80 --> 88.46%.

# Intento 9: k = 150 --> 85.09%.

# Intento 10: k = 300 --> 79.32%. Mínimo.

In [42]:
# 3.2.1 Intento 2: kNN con la distancia de Jaccard.

# Jaccard es una métrica de distancia que se utiliza para datos binarios o categóricos.

x = fichero6.iloc[:, :-1]

y = fichero6.iloc[:, -1]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25)

knn = KNeighborsClassifier(n_neighbors=300, metric='jaccard')

knn.fit(x_train, y_train)

y_pred = knn.predict(x_test)

accuracy = accuracy_score(y_test, y_pred)

print(f'Precisión: {accuracy}')

Precisión: 0.7115384615384616


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [43]:
# 3.2.2 Intento 2: matriz de confusión.

x = fichero6.iloc[:, :6]

y = fichero6['Status']

# Escogemos k=6 porque es el óptimo.

knn = KNeighborsClassifier(n_neighbors=6)

knn.fit(x, y)

y_pred = knn.predict(x)

confm = confusion_matrix(y, y_pred)

print(confm)

[[259   0]
 [  0 570]]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [10]:
# 3.2.3 Intento 2: resultados del kNN según parámetro 'k'.

# Intento 1: k = 2 --> 91.82%.

# Intento 2: k = 4 --> 93.26%. Máximo.

# Intento 3: k = 6 --> 93.26%. Óptimo.

# Intento 4: k = 8 --> 91.82%.

# Intento 5: k = 10 --> 88.46%.

# Intento 6: k = 20 --> 93.26%.

# Intento 7: k = 40 --> 92.78%.

# Intento 8: k = 80 --> 78.84%.

# Intento 9: k = 150 --> 78.84%.

# Intento 10: k = 300 --> 71.15%. Mínimo.

In [53]:
# 3.3.1 Intento 3: kNN con la distancia de Hamming.

# Hamming es una métrica de distancia discreta que se utiliza para datos binarios.

x = fichero6.iloc[:, :-1] 

y = fichero6.iloc[:, -1] 

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25)

knn = KNeighborsClassifier(n_neighbors=300, metric='hamming')

knn.fit(x_train, y_train)

y_pred = knn.predict(x_test)

accuracy = accuracy_score(y_test, y_pred)

print(f'Precisión: {accuracy}')

Precisión: 0.7211538461538461


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [54]:
# 3.3.2 Intento 3: matriz de confusión.

x = fichero6.iloc[:, :6]

y = fichero6['Status']

# Escogemos k=6 porque es el óptimo.

knn = KNeighborsClassifier(n_neighbors=6)

knn.fit(x, y)

y_pred = knn.predict(x)

confm = confusion_matrix(y, y_pred)

print(confm)

[[259   0]
 [  0 570]]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [13]:
# 3.3.3 Intento 3: resultados del kNN según parámetro 'k'.

# Intento 1: k = 2 --> 92.30%.

# Intento 2: k = 4 --> 92.78%. Máximo.

# Intento 3: k = 6 --> 92.78%. Óptimo.

# Intento 4: k = 8 --> 88.94%.

# Intento 5: k = 10 --> 91.82%.

# Intento 6: k = 20 --> 92.30%.

# Intento 7: k = 40 --> 92.78%.

# Intento 8: k = 80 --> 92.78%.

# Intento 9: k = 150 --> 81.25%.

# Intento 10: k = 300 --> 72.11%. Mínimo.

In [14]:
# 3.3 Conclusiones de los resultados.

# a) En primer lugar no podemos descartar que el dataset sea sensible al ruido y
#    al sobreajuste, ya que el 'k' seleccionado es algo reducido. Sin embargo,
#    hay un amplio rango inicial de 'k' que tiene una precisión muy parecida, por
#    lo que tampoco se puede afirmar que tenga sensibilidad al ruido ni sobreajuste.

# b) Por otro lado, los 'k' más grandes tampoco dan la máxima precisión,
#    evitando así, un subajuste.

# c) Por ende, el 'k' óptimo aproximadamente será entre k=6 y k=8. Consideramos que  
#    es un valor razonable, ya que no está cerca del mínimo (k=1) ni supone 
#    un 'k' enorme que de un resultado similar (k=40).

# d) La matriz de confusión es excelente ya que no refleja falsos positivos
#    ni falsos negativos.

# e) Se debe tener en cuenta, de nuevo, que al reiniciar el Kernel y ejecutarlo todo
#    de nuevo los resultados del KNN no tienen por qué ser exactamente el
#    mismo.

In [15]:
# 3.4 Otros posibles intentos.

# Algunas ditancias que se pueden aplizar también son: Manhattan, Chebyshev y Mahalanobis.

# Sin embargo, se ha optado por la Euclídea por ser la predeterminada, la Jaccard y la
# Hamming por estar orientadas a datos binarios. 

# Por otro lado, el resto de distancias:

# Manhattan es una métrica de distancia que se utiliza para datos continuos.

# Chebyshev es una métrica de distancia que se utiliza para datos continuos.

# Mahalanobis es una métrica de distancia que se utiliza para datos multivariados.

In [16]:
# 4. Algoritimos de clasificación y regresión con árboles de decisión

In [59]:
# 4.1.1 Clasificación.

# Los valores predeterminados para los parámetros que controlan el tamaño 
# y el número de hojas en el algoritmo de clasificación de árboles de 
# decisión de scikit-learn conducen a árboles sin podar.

from sklearn.tree import DecisionTreeClassifier

x = fichero6.iloc[:, :-1]

y = fichero6.iloc[:, -1]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25)

clf = DecisionTreeClassifier()

clf.fit(x_train, y_train)

y_pred = clf.predict(x_test)

accuracy = accuracy_score(y_test, y_pred)

print(f'Precisión: {accuracy}')

Precisión: 0.9423076923076923


In [61]:
# 4.1.2 Matriz de confusión.

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[ 55   5]
 [  7 141]]


In [58]:
# 4.2.1 Regresión.

from sklearn.tree import DecisionTreeRegressor

from sklearn.metrics import mean_squared_error

x = fichero6.iloc[:, :-1] 

y = fichero6.iloc[:, -1] 

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25)

reg = DecisionTreeRegressor()

reg.fit(x_train, y_train)

y_pred = reg.predict(x_test)

mse = mean_squared_error(y_test, y_pred)

rmse = np.sqrt(mse)

y_range = y.max() - y.min()

print(f'Error Cuadrático Medio: {mse}')

print(f'Raíz del ECM: {rmse}')

print(f'Rango de la vble endógena: {y_range}')

Error Cuadrático Medio: 0.03897959828264581
Raíz del ECM: 0.19743251576841594
Rango de la vble endógena: 1


In [ ]:
# 4.3 Conclusiones:

# a) La precisión del modelo según el test ha sido de un 94.23%, un resultado
#    similar a los kNN.

# b) El ECM es de 0.038. Por sí mismo no posee valor o interpretación absoluta,
#    pero lo que sí sabemos es que cuanto más cerca del valor cero, mejor.

# c) Por otro lado, el rango de valores de la variable endógena es 1, lo que 
#    significa que la diferencia entre el valor máximo y mínimo de la variable 
#    dependiente es 1 unidad. En este caso, la raíz del ECM es aproximadamente 
#    un 19.74% del rango de valores. Esto sugiere que las predicciones del 
#    modelo son bastante precisas.

# d) La matriz de confusión proviene del 25% de 829 que es 208. Por otra parte, 
#    apenas posee falsos positivos y falsos negativos, lo cual es un signo positivo.